from cx4 cimport cx

CXDTYPE_UNKNOWN = cx.CXDTYPE_UNKNOWN
CXDTYPE_INT8 = cx.CXDTYPE_INT8
CXDTYPE_INT16 = cx.CXDTYPE_INT16
CXDTYPE_INT32 = cx.CXDTYPE_INT32
CXDTYPE_INT64 = cx.CXDTYPE_INT64
CXDTYPE_UINT8 = cx.CXDTYPE_UINT8
CXDTYPE_UINT16 = cx.CXDTYPE_UINT16
CXDTYPE_UINT32 = cx.CXDTYPE_UINT32
CXDTYPE_UINT64 = cx.CXDTYPE_UINT64
CXDTYPE_SINGLE = cx.CXDTYPE_SINGLE
CXDTYPE_DOUBLE = cx.CXDTYPE_DOUBLE
CXDTYPE_TEXT = cx.CXDTYPE_TEXT
CXDTYPE_UCTEXT = cx.CXDTYPE_UCTEXT
