#cython: profile=False, linetrace=False
#cython: c_string_type=bytes, c_string_encoding=ascii
#cython: boundscheck=False, wraparound=False


from cda cimport *

# cx data types

PY_CXDTYPE_UNKNOWN = CXDTYPE_UNKNOWN
PY_CXDTYPE_INT8 = CXDTYPE_INT8
PY_CXDTYPE_INT16 = CXDTYPE_INT16
PY_CXDTYPE_INT32 = CXDTYPE_INT32
PY_CXDTYPE_INT64 = CXDTYPE_INT64
PY_CXDTYPE_UINT8 = CXDTYPE_UINT8
PY_CXDTYPE_UINT16 = CXDTYPE_UINT16
PY_CXDTYPE_UINT32 = CXDTYPE_UINT32
PY_CXDTYPE_UINT64 = CXDTYPE_UINT64
PY_CXDTYPE_SINGLE = CXDTYPE_SINGLE
PY_CXDTYPE_DOUBLE = CXDTYPE_DOUBLE
PY_CXDTYPE_TEXT = CXDTYPE_TEXT
PY_CXDTYPE_UCTEXT = CXDTYPE_UCTEXT
